name: Test compilation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-certicoq.opam'
        image:
          - 'ghcr.io/womeier/certicoqwasm:2.0'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "Copy repo (for later benchmarking)"
              cp -r `pwd` ~/repo
            endGroup
            startGroup "opam pin"
              opam pin -n -y submodules/metacoq
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
            startGroup "Run benchmarks"
              sudo apt-get install --yes wabt nodejs
              ulimit -s unlimited
              make -C ~/repo/benchmarks all
            endGroup
            startGroup "Test bootstrapped plugins"
              make -C ~/repo/bootstrap test
            endGroup
