name: Test compilation

on:
  push:
    branches:
      - master
      - migrate-wasm
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-certicoq.opam'
        image:
          - 'ghcr.io/womeier/certicoqwasm:4.0'
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "Copy repo (for later benchmarking)"
              cp -r `pwd` ~/repo
            endGroup
            startGroup "clone subrepos"
              sudo chmod 777 . -R
              sudo chmod 777 ~/.opam/ -R
              git config --global --add safe.directory /github/workspace
              git config --global --add safe.directory /github/workspace/submodules/wasmcert
              git config --global --add safe.directory /github/workspace/submodules/strong-induction
              git config --global --add safe.directory /github/workspace/submodules/metacoq
              git config --global --add safe.directory /github/workspace/submodules/parseque
              git submodule update --init
            endGroup
            startGroup "Install some more opam packages"
              opam repo add coq-released https://coq.inria.fr/opam/released
              opam update
              opam pin -y coq-mathcomp-ssreflect 1.16.0
              opam install coq-mathcomp-ssreflect
              opam pin -y coq-itree 5.1.1
              opam install coq-itree

              cd ~/repo
              opam pin -n -y  submodules/metacoq # was pinned to the submodule at the same path in the dockerfile before -> is not rebuilt
            endGroup

            startGroup "Make submodules"
              cd ~/repo/submodules/
              git submodule update --init

              cd strong-induction
              echo "Building Strong-Induction"
              make
              make install
              cd ..

              cd parseque
              echo "Building parseque"
              make
              make install
              cd ..

              cd wasmcert
              echo "Building wasmcert"
              make
              make install
              cd ..

              cd ..
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
            startGroup "Run benchmarks"
              sudo apt-get install --yes wabt nodejs
              ulimit -s unlimited
              make -C ~/repo/benchmarks all
            endGroup
            startGroup "Test bootstrapped plugins"
              make -C ~/repo/bootstrap test
            endGroup
